# Generated by Django 4.0.3 on 2024-04-13 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_writing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing_model',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writing_model',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
